=== threehook/ontmalizer-client/src/test/resources/test/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:salus="http://www.salusproject.eu/ontology/test" targetNamespace="http://www.salusproject.eu/ontology/test" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="roott" type="salus:Roott">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="Roott">
		<xs:sequence>
			<xs:element name="elem1" type="xs:string"/>
			<xs:element name="elem2" type="xs:int" maxOccurs="5"/>
			<xs:element name="elem3" type="salus:simpletype1" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="elem4" type="salus:simpletype2" minOccurs="0"/>
			<xs:element name="elem5" type="salus:simpletype5" maxOccurs="unbounded"/>
			<xs:element name="elem6" type="salus:complextype1" maxOccurs="unbounded"/>
			<xs:element name="elemSimpleAndComplex" type="salus:complextype3"/>
		</xs:sequence>
		<xs:attribute name="attr1" type="xs:string"/>
		<xs:attribute name="attr2" type="xs:int"/>
		<xs:attribute name="attr3" type="salus:simpletype3"/>
		<xs:attribute name="attr4" type="salus:simpletype4"/>
		<xs:attribute name="attr5" type="salus:simpletype6"/>
	</xs:complexType>
	<xs:complexType name="complextype1">
		<xs:sequence>
			<xs:element name="ctelem1" type="xs:string"/>
			<xs:element name="ctelem2" type="salus:simpletype2" minOccurs="0"/>
			<xs:element name="ctelem3" type="salus:simpletype5" maxOccurs="unbounded"/>
			<xs:element name="ctelem4" type="salus:complextype2" minOccurs="0"/>
			<xs:element name="elemSimpleAndComplex" type="salus:simpletype1"/>
		</xs:sequence>
		<xs:attribute name="ctattr1" type="xs:string"/>
		<xs:attribute name="ctattr2" type="salus:simpletype1"/>
	</xs:complexType>
	<xs:complexType name="complextype2" mixed="true">
		<xs:attribute name="mixedattr1" type="xs:string"/>
		<xs:attribute name="mixedattr2" type="salus:simpletype1"/>
	</xs:complexType>
	<xs:complexType name="complextype3">
		<xs:sequence>
			<xs:element name="cmp3elem1" type="xs:float"/>
		</xs:sequence>
		<xs:attribute name="cmp3attr1" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="simpletype1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NP"/>
			<xs:enumeration value="NI"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="simpletype2">
		<xs:union memberTypes="xs:string xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="simpletype3">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MSK"/>
			<xs:enumeration value="NA"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="simpletype4">
		<xs:union memberTypes="xs:int xs:float"/>
	</xs:simpleType>
	<xs:simpleType name="simpletype5">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="simpletype6">
		<xs:restriction base="xs:string">
			<xs:minLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== threehook/ontmalizer-client/src/test/resources/test/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 sp1 (http://www.altova.com)-->
<salus:roott attr1="attr1val" attr2="2" attr3="MSK" attr4="4" attr5="attr5val" xmlns:salus="http://www.salusproject.eu/ontology/test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.salusproject.eu/ontology/test test.xsd">
	<salus:elem1>elem1val</salus:elem1>
	<salus:elem2>22</salus:elem2>
	<salus:elem3>NP</salus:elem3>
	<salus:elem4>elem4val</salus:elem4>
	<salus:elem5>elem5val</salus:elem5>
	<salus:elem6 ctattr1="ctattr1val" ctattr2="NP">
		<salus:ctelem1>ctelem1val</salus:ctelem1>
		<salus:ctelem2>ctelem2val</salus:ctelem2>
		<salus:ctelem3>ctelem3val</salus:ctelem3>
		<salus:ctelem4 mixedattr1="mixedattr1val" mixedattr2="NI">ctelem4val</salus:ctelem4>
		<salus:elemSimpleAndComplex>NP</salus:elemSimpleAndComplex>
	</salus:elem6>
	<salus:elemSimpleAndComplex>
		<salus:cmp3elem1>3.14</salus:cmp3elem1>
	</salus:elemSimpleAndComplex>
</salus:roott>
